My cal
uehara-san/ruby-practices pull request #2
Opened 2022-07-09 04:22 UTC by uehara-san

ご確認お願いいたします。

2022-07-10 08:16 UTC, func09 requested changes
確認しましたー、

* 他の提出物がまじっている
* 最終日に改行されてほしい

の２点、修正をお願いします！

2022-07-10 08:16 UTC, func09 commented on 01.fizzbuzz/FizzBuzz.rb
> +(1..20).each do |num|
FizzBuzzのコードが入ってしまってますね。

https://github.com/fjordllc/ruby-practices/pull/157/files

READMEなどを見つつ、複数課題が混ざっていない状態の提出物になるようにお願いします！

2022-07-10 08:16 UTC, func09 commented on 02.calendar/cal.rb
> +  end
```ruby
print sprintf("%2d ", x.day)
```

数字を幅を２桁分に調整して、後ろにスペースを置きたい場合、こんな感じに記述することもできます。
ご参考までに。

2022-07-10 08:16 UTC, func09 commented on 02.calendar/cal.rb
> +  end
<img width="452" alt="-zsh" src="https://user-images.githubusercontent.com/34449/178136922-33bbc8c9-31ba-4dcd-bacb-bd4d56d68fc8.png">

土曜日の後に改行されるのは良いのですが、最終日の後にも改行されるようにしてみてほしいです〜。

2022-07-15 03:42 UTC, uehara-san commented on 01.fizzbuzz/FizzBuzz.rb
> +(1..20).each do |num|
削除いたしました。

2022-07-15 03:42 UTC, uehara-san commented on 02.calendar/cal.rb
> +  end
勉強になります。
ありがとうございます。

2022-07-15 04:48 UTC, uehara-san commented on 02.calendar/cal.rb
> +  end
指摘された箇所を修正いたしましたのでご確認お願いいたします。

2022-07-15 05:30 UTC, func09 approved these changes
確認しました LGTMです！

2022-07-15 09:15 UTC, merged

2022-07-15 09:16 UTC, uehara-san commented
ありがとうございます。
マージします。